get:
  summary: The base endpoint everyone can go through
  operationId: root
  tags:
    - Root
  responses:
    200:
      description: Expected response to a valid request
      content:
        application/json:
          schema:
            type: object
            required:
              - text
            properties:
              text:
                $ref: '../../specifications/components.yaml#/components/schemas/text'
      links:
        Ping:
          $ref: '../../specifications/components.yaml#/components/links/Ping'
        Specification:
          $ref: '../../specifications/components.yaml#/components/links/Specification'
        SwaggerUI:
          $ref: '../../specifications/components.yaml#/components/links/SwaggerUI'
        Versions:
          $ref: '../../specifications/components.yaml#/components/links/Versions'
    400:
      $ref: '../../specifications/components.yaml#/components/responses/400'
    500:
      $ref: '../../specifications/components.yaml#/components/responses/500'
    502:
      $ref: '../../specifications/components.yaml#/components/responses/502'
