get:
  summary: The base endpoint everyone can go through
  operationId: root
  tags:
    - Root
  responses:
    200:
      description: Expected response to a valid request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                $ref: '../../specifications/components.yaml#/components/schemas/message'
      links:
        Ping:
          $ref: '../../specifications/components.yaml#/components/links/Ping'
    500:
      $ref: '../../specifications/components.yaml#/components/responses/500'
