get:
  summary: Retrieve a player details
  operationId: getPlayerDetails
  tags:
    - Player
  parameters:
    - in: path
      name: id
      required: true
      schema:
        $ref: '../../../specifications/components.yaml#/components/schemas/id'
  responses:
    200:
      description: Player details
      content:
        'application/json':
          schema:
            type: object
            required:
              - player
              - nearby
              - text
            properties:
              player:
                type: object
                required:
                  - currentPosition
                  - id
                  - name
                properties:
                  currentPosition:
                    $ref: '../../../specifications/components.yaml#/components/schemas/coordinates'
                  id:
                    $ref: '../../../specifications/components.yaml#/components/schemas/id'
                  name:
                    $ref: '../../../specifications/components.yaml#/components/schemas/name'
              nearby:
                type: array
                items:
                  type: object
                  required:
                    - currentPosition
                    - id
                  properties:
                    currentPosition:
                      $ref: '../../../specifications/components.yaml#/components/schemas/coordinates'
                    id:
                      $ref: '../../../specifications/components.yaml#/components/schemas/id'
              text:
                $ref: '../../../specifications/components.yaml#/components/schemas/text'
    400:
      $ref: '../../../specifications/components.yaml#/components/responses/400'
    500:
      $ref: '../../../specifications/components.yaml#/components/responses/500'
    502:
      $ref: '../../../specifications/components.yaml#/components/responses/502'
