get:
  summary: Retrieve a short message to ensure service is running properly
  operationId: selfHealthPing
  tags:
    - self-health
  responses:
    200:
      description: Expected response to a valid request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                $ref: '../../../specifications/components.yaml#/components/schemas/message'
      links:
        Ping:
          $ref: '../../../specifications/components.yaml#/components/links/Ping'
    500:
      $ref: '../../../specifications/components.yaml#/components/responses/500'
