post:
  summary: Spawn a new player with given username
  operationId: createPlayer
  tags:
    - Player
  requestBody:
    required: true
    description: Informations for player creation
    content:
      'application/json':
        schema:
          type: object
          required:
            - username
          properties:
            username:
              $ref: '../../../specifications/components.yaml#/components/schemas/username'
  responses:
    201:
      description: New player entity
      content:
        application/json:
          schema:
            type: object
            properties:
              username:
                $ref: '../../../specifications/components.yaml#/components/schemas/username'
      links:
        Ping:
          operationRef: /self-health/ping
          description: >
            You can use this endpoint to test whether the server is online.
    500:
      $ref: '../../../specifications/components.yaml#/components/responses/500'
