post:
  summary: Spawn a new player with given name
  operationId: addNewPlayer
  tags:
    - Player
  requestBody:
    required: true
    description: Informations for player creation
    content:
      'application/json':
        schema:
          type: object
          required:
            - name
          properties:
            name:
              $ref: '../../../specifications/components.yaml#/components/schemas/name'
  responses:
    201:
      description: New player entity
      content:
        'application/json':
          schema:
            type: object
            required:
              - player
              - spaceship
            properties:
              player:
                type: object
                required:
                  - id
                  - name
                properties:
                  id:
                    $ref: '../../../specifications/components.yaml#/components/schemas/id'
                  name:
                    $ref: '../../../specifications/components.yaml#/components/schemas/name'
              spaceship:
                type: object
                required:
                  - currentPosition
                  - id
                  - name
                properties:
                  currentPosition:
                    $ref: '../../../specifications/components.yaml#/components/schemas/coordinates'
                  id:
                    $ref: '../../../specifications/components.yaml#/components/schemas/id'
                  name:
                    $ref: '../../../specifications/components.yaml#/components/schemas/name'
      links:
        Ping:
          $ref: '../../../specifications/components.yaml#/components/links/Ping'
    400:
      $ref: '../../../specifications/components.yaml#/components/responses/400'
    500:
      $ref: '../../../specifications/components.yaml#/components/responses/500'
    502:
      $ref: '../../../specifications/components.yaml#/components/responses/502'
