post:
  summary: Spawn a new player with given username
  operationId: addNewPlayer
  tags:
    - Player
  requestBody:
    required: true
    description: Informations for player creation
    content:
      'application/json':
        schema:
          type: object
          required:
            - username
          properties:
            username:
              $ref: '../../../specifications/components.yaml#/components/schemas/username'
  responses:
    201:
      description: New player entity
      content:
        application/json:
          schema:
            type: object
            properties:
              username:
                $ref: '../../../specifications/components.yaml#/components/schemas/username'
      links:
        Ping:
          $ref: '../../../specifications/components.yaml#/components/links/Ping'
    500:
      $ref: '../../../specifications/components.yaml#/components/responses/500'
