openapi: '3.0.0'

info:
  version: 1.0.0
  title: Space RPG API
  description: A Space RPG that can be experienced through a REST API
  license:
    name: GPL v3.0

servers:
  - url: http://localhost:9000

paths:
  /:
    $ref: 'src/handlers/root/openapi.yaml'
  /openapi:
    $ref: 'src/handlers/specification/openapi.yaml'
  /self-health/ping:
    $ref: 'src/handlers/miscellaneous/self-health/openapi.yaml'
  /player/create:
    $ref: 'src/handlers/player/create/openapi.yaml'
  /displacement/{id}:
    $ref: 'src/handlers/displacement/openapi.yaml'
  /displacement/start:
    $ref: 'src/handlers/displacement/start/openapi.yaml'

components:
  schemas:
    ServiceError:
      $ref: './src/specifications/components.yaml#/components/schemas/ServiceError'
    message:
      $ref: './src/specifications/components.yaml#/components/schemas/message'
