openapi: '3.0.0'

info:
  version: 1.0.0
  title: Space RPG API
  description: A Space RPG that can be experienced through a REST API
  license:
    name: GPL v3.0

servers:
  - url: https://space-rpg-api.herokuapp.com
  - url: http://localhost:9000

paths:
  /:
    $ref: 'src/handlers/root/openapi.yaml'
  /specification:
    $ref: 'src/handlers/miscellaneous/specification/openapi.yaml'
  /swagger-ui/:
    get:
      description: A SwaggerUI front-end that is based on this specification.
      summary: SwaggerUI
      tags:
        - Root
      responses:
        200:
          description: SwaggerUI index.html page
          content:
            text/html:
              schema:
                type: string
  /self-health/ping:
    $ref: 'src/handlers/miscellaneous/self-health/openapi.yaml'
  /player/{id}:
    $ref: 'src/handlers/player/details/openapi.yaml'
  /player/create:
    $ref: 'src/handlers/player/create/openapi.yaml'
  /displacement/{id}:
    $ref: 'src/handlers/displacement/details/openapi.yaml'
  /displacement/travelToPosition:
    $ref: 'src/handlers/displacement/travelToPosition/openapi.yaml'
